#!/usr/bin/awk -f

BEGIN { FS="," }

/^;/ {next}

$1 == "Zone" {
	cur_zone = $2
	cur_net = 1
	cur_node = 0
	prefix = "ZONE "
}

$1 == "Host" {
	cur_net = $2
	cur_node = 0
	prefix = "HOST "
}

$1 != "Host" && $1 != "Zone" {
	cur_node = $2
}

onlyzone == "" || onlyzone == cur_zone {
	printf "%s[%s:%s/%s] %s\n", prefix, cur_zone, cur_net, cur_node, $0
	prefix=""
}

