#!/usr/bin/python

import os, sys, optparse, zipfile
from pydonet.packet import Packet

def parse_args():
	parser = optparse.OptionParser()
	parser.add_option('-z', '--zip', action='store_true')
	parser.add_option('-o', '--output-dir')

	return parser.parse_args()

def findNextMessage(dir):
	num = 2
	while os.path.exists(os.path.join(dir, '%d.msg' % num)):
		num += 1

	return os.path.join(dir, '%d.msg' % num)

def scanPacket(pkt, opts):
	print 'Header:'
	print repr(pkt.header)

	print 'Messages:'
	count = 0
	for msg in pkt:
		outpath = findNextMessage(opts.output_dir)
		fd = open(outpath, 'w')
		fd.write(msg.serialize())
		fd.close()
		print '[%d]' % count, msg
		print '     (Written to %s)' % outpath
		count += 1

	print 'Found %d messages.' % count

def main():
	opts, args = parse_args()

	for arg in args:
		print 'FILE:', arg
		if opts.zip:
			zf = zipfile.ZipFile(arg)
			for name in zf.namelist():
				pkt = Packet(data = zf.read(name))
				scanPacket(pkt, opts)
		else:
			pkt = Packet(file = arg)
			scanPacket(pkt, opts)

if __name__ == '__main__': main()

