#!/usr/bin/python

import os, sys
from pydonet.formats.dbridge import ADF

STORAGETYPE = {
  'F':  'FTS-0001',
  'Q':  'QuickBBS',
  'N':  'Passthru'
}

AREATYPE = {
  'E':  'Echomail',
  'L':  'Local'
}

def main():
  fd = open(sys.argv[1])
  areas = ADF.parse_stream(fd)
  fd.close()

  anum = 0
  for area in areas:
    anum += 1
    if not area.allocated: continue
    print '[%03d]' % anum, '%s: %s' % (area.areaName.val, area.areaDesc.val)
    print ' ' * 5, '%s %s area in %s' % (STORAGETYPE[area.storage], 
      AREATYPE[area.kind],
      area.directoryPath.val)

if __name__ == '__main__': main()

